version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: gincana-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gincana
      POSTGRES_PASSWORD: gincana
      POSTGRES_DB: gincana_educativa
    ports:
      - "5432:5432"
    volumes:
      - gincana_postgres_data:/var/lib/postgresql/data

volumes:
  gincana_postgres_data:
